const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Plugins.progressbar,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.MoveTo.Acts.MoveAlongPathfindingPath,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Exps.CurrentTime,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetTowardPosition
	];
};
self.C3_JsPropNameTable = [
	{cartev1_tunnelspluslarges: 0},
	{"8Directions": 0},
	{DéfilerVers: 0},
	{LigneDeMire: 0},
	{vers: 0},
	{Solide: 0},
	{murs: 0},
	{Clavier: 0},
	{Souris: 0},
	{ChercheChemin: 0},
	{DéplacerVers: 0},
	{ennemy: 0},
	{Ancre: 0},
	{BarreDeProgression: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{petite_racinepourrie1: 0},
	{petite_racinepourrie2: 0},
	{moyenne_racinepourrie1: 0},
	{grosse_racinepourrie2: 0},
	{grosse_racinepourrie1: 0},
	{coin: 0},
	{obstacle1_caillou: 0},
	{munitions: 0},
	{texteMunitions: 0},
	{Sprite5: 0},
	{projectile_antiracines2: 0},
	{Interface: 0},
	{texteMunitions2: 0},
	{texteCoin: 0},
	{texteCoinObjectif: 0},
	{fond_rapidev: 0},
	{zone1: 0},
	{zone2: 0},
	{zone3: 0},
	{zone4: 0},
	{obst_caillou: 0},
	{obst_caillou2: 0},
	{vrmtpourries: 0},
	{vrmtpourries2: 0},
	{vrmtpourries3: 0},
	{vrmtpourries4: 0},
	{vrmtpourries5: 0},
	{moyenCoin: 0},
	{petitCoin: 0},
	{obstacle2_plastique: 0},
	{obstacle2_plastique2: 0},
	{obstacle2_plastique3: 0},
	{bact_aerobie3_clusterrare: 0},
	{fov3: 0},
	{Trace: 0},
	{TexteScoreZone1: 0},
	{TexteScoreZone2: 0},
	{TexteScoreZone3: 0},
	{TexteScoreZone4: 0},
	{TexteScore: 0},
	{Sprite6: 0},
	{ciel2fourche: 0},
	{Sprite7: 0},
	{Audio: 0},
	{texteIntro: 0},
	{Interrogation: 0},
	{texteObjectif: 0},
	{textePlastique: 0},
	{texteRacine: 0},
	{explicationsplastique: 0},
	{explicationsracines: 0},
	{explicationCoin: 0},
	{ToucheE: 0},
	{ToucheA: 0},
	{iconcoin: 0},
	{iconplastique: 0},
	{iconracines: 0},
	{Touchezqsd: 0},
	{zone: 0},
	{zonesObjectif: 0},
	{Sprite8: 0},
	{acarien: 0},
	{boule: 0},
	{texture: 0},
	{texture2: 0},
	{gameoverULTIMATEVERSION: 0},
	{victoire: 0},
	{Crédit: 0},
	{Crédit2: 0},
	{ancreFleche: 0},
	{acceleration: 0},
	{Munitions: 0},
	{destruction: 0},
	{munitionplastique: 0},
	{destructionplastique: 0},
	{scoreZone1: 0},
	{scoreZone2: 0},
	{scoreZone3: 0},
	{scoreZone4: 0},
	{positionLectureTHEME: 0},
	{positionLectureAMBIANCE: 0},
	{distanceZone1: 0},
	{distanceZone2: 0},
	{distanceZone3: 0},
	{distanceZone4: 0}
];

self.InstanceType = {
	cartev1_tunnelspluslarges: class extends self.ISpriteInstance {},
	vers: class extends self.ISpriteInstance {},
	murs: class extends self.ISpriteInstance {},
	Clavier: class extends self.IInstance {},
	Souris: class extends self.IInstance {},
	ennemy: class extends self.ISpriteInstance {},
	BarreDeProgression: class extends self.IProgressBarInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	petite_racinepourrie1: class extends self.ISpriteInstance {},
	petite_racinepourrie2: class extends self.ISpriteInstance {},
	moyenne_racinepourrie1: class extends self.ISpriteInstance {},
	grosse_racinepourrie2: class extends self.ISpriteInstance {},
	grosse_racinepourrie1: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	obstacle1_caillou: class extends self.ISpriteInstance {},
	munitions: class extends self.ISpriteInstance {},
	texteMunitions: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	projectile_antiracines2: class extends self.ISpriteInstance {},
	Interface: class extends self.ISpriteInstance {},
	texteMunitions2: class extends self.ITextInstance {},
	texteCoin: class extends self.ITextInstance {},
	texteCoinObjectif: class extends self.ITextInstance {},
	fond_rapidev: class extends self.ISpriteInstance {},
	zone1: class extends self.ISpriteInstance {},
	zone2: class extends self.ISpriteInstance {},
	zone3: class extends self.ISpriteInstance {},
	zone4: class extends self.ISpriteInstance {},
	obst_caillou: class extends self.ISpriteInstance {},
	obst_caillou2: class extends self.ISpriteInstance {},
	vrmtpourries: class extends self.ISpriteInstance {},
	vrmtpourries2: class extends self.ISpriteInstance {},
	vrmtpourries3: class extends self.ISpriteInstance {},
	vrmtpourries4: class extends self.ISpriteInstance {},
	vrmtpourries5: class extends self.ISpriteInstance {},
	moyenCoin: class extends self.ISpriteInstance {},
	petitCoin: class extends self.ISpriteInstance {},
	obstacle2_plastique: class extends self.ISpriteInstance {},
	obstacle2_plastique2: class extends self.ISpriteInstance {},
	obstacle2_plastique3: class extends self.ISpriteInstance {},
	bact_aerobie3_clusterrare: class extends self.ISpriteInstance {},
	fov3: class extends self.ISpriteInstance {},
	Trace: class extends self.ISpriteInstance {},
	TexteScoreZone1: class extends self.ITextInstance {},
	TexteScoreZone2: class extends self.ITextInstance {},
	TexteScoreZone3: class extends self.ITextInstance {},
	TexteScoreZone4: class extends self.ITextInstance {},
	TexteScore: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ciel2fourche: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	texteIntro: class extends self.ISpriteInstance {},
	Interrogation: class extends self.ITextInstance {},
	texteObjectif: class extends self.ISpriteInstance {},
	textePlastique: class extends self.ISpriteInstance {},
	texteRacine: class extends self.ISpriteInstance {},
	explicationsplastique: class extends self.ISpriteInstance {},
	explicationsracines: class extends self.ISpriteInstance {},
	explicationCoin: class extends self.ISpriteInstance {},
	ToucheE: class extends self.ITextInstance {},
	ToucheA: class extends self.ITextInstance {},
	iconcoin: class extends self.ISpriteInstance {},
	iconplastique: class extends self.ISpriteInstance {},
	iconracines: class extends self.ISpriteInstance {},
	Touchezqsd: class extends self.ITextInstance {},
	zone: class extends self.ITextInstance {},
	zonesObjectif: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	acarien: class extends self.ISpriteInstance {},
	boule: class extends self.ISpriteInstance {},
	texture: class extends self.ISpriteInstance {},
	texture2: class extends self.ISpriteInstance {},
	gameoverULTIMATEVERSION: class extends self.ISpriteInstance {},
	victoire: class extends self.ISpriteInstance {},
	Crédit: class extends self.ITextInstance {},
	Crédit2: class extends self.ITextInstance {},
	ancreFleche: class extends self.ISpriteInstance {}
}